version: "3.8"

services:

  client:
    image: avrilm/capstone:frontend-latest
    environment:
        - REACT_APP_PAYPAL_CLIENT_ID=${REACT_APP_PAYPAL_CLIENT_ID}
    ports: 
        - "80:3000"

  server:
    image: avrilm/capstone:backend-latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      
    ports:
      - "3001:3001"

     
          
          
          