version: "3.8"

services:
  nginx:
    image: avrilm/capstone:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: avrilm/capstone:frontend-latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}

  server:
    image: avrilm/capstone:backend-latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_USER=${EMAIL_USER}
      - PORT=${PORT}
    ports:
      - "3001:3001"

     
          
          
          