version: '3'

services:

  server:
        build: ./server
        expose:
            - 3001
        ports:
            - 3001:3001
        volumes:
            - ./server/src:/app/src
        depends_on:
            - mongo    
        command: npm run start
        env_file:
        - ./server/.env  

  client:
        build: ./client
        expose:
            - 3000   
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/app/src
            - ./client/public:/app/public
        stdin_open: true
        command: npm run start
        env_file:
        - ./client/.env  

  mongo:
        image: mongo
        ports:
            - "27017:27017"

        
