
      # # Push the Docker images to Docker Hub
      # - name: Push Docker Images to Docker Hub
      #   run: |
      #     docker push rakeshpotnuru/productivity-app:client-${{github.run_number}}
      #     docker push rakeshpotnuru/productivity-app:server-${{github.run_number}}
      #     docker push rakeshpotnuru/productivity-app:nginx-${{github.run_number}}
      #     docker push rakeshpotnuru/productivity-app:client-latest
      #     docker push rakeshpotnuru/productivity-app:server-latest
      #     docker push rakeshpotnuru/productivity-app:nginx-latest
      # # This is the step that is deploying the application to Elastic Beanstalk.
      # - name: Deploy to Elastic Beanstalk
      #   uses: einaregilsson/beanstalk-deploy@v21
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: ${{ secrets.EB_APP_NAME }}
      #     environment_name: ${{ secrets.EB_ENV_NAME }}
      #     region: ${{ secrets.EB_REGION }}
      #     version_label: "version-${{ github.run_number }}"
      #     deployment_package: docker-compose.yml